global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'dlogs-internal'
    static_configs:
      - targets: ['dlogs-prometheus:9090', 'dlogs-cadvisor:8080']

  - job_name: 'node-exporter'
    file_sd_configs:
      - files: ['/etc/prometheus/generated/node-exporter.json']
  
  # Connect to Host Machine (Windows/Linux Native)
  - job_name: 'host-machine'
    file_sd_configs:
      - files: ['/etc/prometheus/generated/host-machine.json']

  - job_name: 'gpu'
    file_sd_configs:
      - files: ['/etc/prometheus/generated/gpu.json']
